# Generated by Django 5.1.6 on 2025-02-25 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.IntegerField(default=0)),
                ('Package_place', models.CharField(max_length=100)),
                ('days_stay', models.CharField(max_length=200)),
                ('price_per_person', models.CharField(default=0, max_length=100)),
                ('Description', models.TextField(default=0, max_length=500)),
                ('Image_related_to_package', models.ImageField(upload_to='gallery/')),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Userregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_Number', models.CharField(default=0, max_length=15)),
                ('Place', models.CharField(default=0, max_length=100)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendorregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=100)),
                ('Company_name', models.CharField(default=0, max_length=150)),
                ('Address', models.TextField(default=0)),
                ('Phone_Number', models.CharField(default=0, max_length=15)),
                ('Year_established', models.PositiveBigIntegerField(default=0)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booknow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=100)),
                ('Contact_Number', models.CharField(max_length=15)),
                ('Email', models.EmailField(default=0, max_length=254)),
                ('No_of_persons', models.IntegerField()),
                ('No_of_Childrens', models.CharField(default=0, max_length=50)),
                ('Booking_reservation', models.CharField(default=0, max_length=50)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userregistration')),
            ],
        ),
    ]
