# Generated by Django 5.1.6 on 2025-03-05 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_booknow_booking_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booknow',
            old_name='Booking_reservation',
            new_name='Booking_reservation_date',
        ),
    ]
